config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issue_book_dates
  resources :books
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :issuebookdate
  has_many :user , through: :issuebookdate
end

app/models/issue_book_date.rb
class IssueBookDate < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :issuebookdate
  has_many :book , through: :issuebookdate

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except:[:show, :index]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def requests
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :published_at, :request)
    end
end

app/controllers/issue_book_dates_controller.rb
class IssueBookDatesController < ApplicationController
  before_action :set_issue_book_date, only: %i[ show edit update destroy ]

  # GET /issue_book_dates or /issue_book_dates.json
  def index
    @issue_book_dates = IssueBookDate.all
  end

  # GET /issue_book_dates/1 or /issue_book_dates/1.json
  def show
  end

  # GET /issue_book_dates/new
  def new
    @issue_book_date = IssueBookDate.new
  end

  # GET /issue_book_dates/1/edit
  def edit
  end

  # POST /issue_book_dates or /issue_book_dates.json
  def create
    @issue_book_date = IssueBookDate.new(issue_book_date_params)

    respond_to do |format|
      if @issue_book_date.save
        format.html { redirect_to @issue_book_date, notice: "Issue book date was successfully created." }
        format.json { render :show, status: :created, location: @issue_book_date }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue_book_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issue_book_dates/1 or /issue_book_dates/1.json
  def update
    respond_to do |format|
      if @issue_book_date.update(issue_book_date_params)
        format.html { redirect_to @issue_book_date, notice: "Issue book date was successfully updated." }
        format.json { render :show, status: :ok, location: @issue_book_date }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue_book_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issue_book_dates/1 or /issue_book_dates/1.json
  def destroy
    @issue_book_date.destroy
    respond_to do |format|
      format.html { redirect_to issue_book_dates_url, notice: "Issue book date was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue_book_date
      @issue_book_date = IssueBookDate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_book_date_params
      params.require(:issue_book_date).permit(:issuedate, :user_id, :book_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/issue_book_dates_helper.rb
module IssueBookDatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.text_field :published_at %>
  </div>

  <div class="field">
    <%= form.label :request %>
    <%= form.text_field :request %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published at</th>
      <th>Request</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.published_at %></td>
        <td><%= book.request %></td>
        <td><%= book.user %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @book.published_at %>
</p>

<p>
  <strong>Request:</strong>
  <%= @book.request %>
</p>

<p>
  <strong>User:</strong>
  <%= @book.user %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/issue_book_dates/_form.html.erb
<%= form_with(model: issue_book_date, local: true) do |form| %>
  <% if issue_book_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue_book_date.errors.count, "error") %> prohibited this issue_book_date from being saved:</h2>

      <ul>
      <% issue_book_date.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :issuedate %>
    <%= form.datetime_select :issuedate %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issue_book_dates/edit.html.erb
<h1>Editing Issue Book Date</h1>

<%= render 'form', issue_book_date: @issue_book_date %>

<%= link_to 'Show', @issue_book_date %> |
<%= link_to 'Back', issue_book_dates_path %>

app/views/issue_book_dates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issue Book Dates</h1>

<table>
  <thead>
    <tr>
      <th>Issuedate</th>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issue_book_dates.each do |issue_book_date| %>
      <tr>
        <td><%= issue_book_date.issuedate %></td>
        <td><%= issue_book_date.user %></td>
        <td><%= issue_book_date.book %></td>
        <td><%= link_to 'Show', issue_book_date %></td>
        <td><%= link_to 'Edit', edit_issue_book_date_path(issue_book_date) %></td>
        <td><%= link_to 'Destroy', issue_book_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue Book Date', new_issue_book_date_path %>

app/views/issue_book_dates/new.html.erb
<h1>New Issue Book Date</h1>

<%= render 'form', issue_book_date: @issue_book_date %>

<%= link_to 'Back', issue_book_dates_path %>

app/views/issue_book_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issuedate:</strong>
  <%= @issue_book_date.issuedate %>
</p>

<p>
  <strong>User:</strong>
  <%= @issue_book_date.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @issue_book_date.book %>
</p>

<%= link_to 'Edit', edit_issue_book_date_path(@issue_book_date) %> |
<%= link_to 'Back', issue_book_dates_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the Library Management System</h1>

<% if current_user %>


<%= link_to "Book List",  books_path %>

<%= link_to "BooksIssueDates", issue_book_dates_path %>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

<% else %>

<%= link_to "Sign up", new_user_registration_path %>

<%= link_to "Sign in ", new_user_session_path %>

<% end %>